### ISSUE TITLE
Disabled modules should not show

### ISSUE THREAD

**Issue by netmindz** [ewoudwijma/StarMod#32]
If you have disabled a module, I would not expect to still see that in the UI

**Comment by ewoudwijma** [comment]
Solved in https://github.com/ewowi/StarMod/commit/b8e9ca3ba4df788ece58e0875cafdb120ef2b88c

Please close if confirmed

**Comment by ewoudwijma** [comment]
Closing this.
Please reopen if you think it is not solved
