### ISSUE TITLE
No indication of audio effect

### ISSUE THREAD

**Issue by netmindz** [ewoudwijma/StarMod#36]
Can't tell from effect list which need audio data

**Comment by ewoudwijma** [comment]
Not sure yet if I want to add it by adding a 🎶 in the name.
Maybe all effects react to sound in the future 🙂.
(Eg effect class will get a function 'onBeat' which goes to the next frame or whatever )

What I want to add is grouping of effects, a special type of dropdown need to be designed which shows this grouping (and also allows for search).
So core sound effects could be added in a special group

**Comment by ewoudwijma** [comment]
New solution:

<img width="158" alt="image" src="https://github.com/ewowi/StarMod/assets/1737159/3ccea95f-97b6-4db3-b24f-38527cb121bd">

See https://ewowi.github.io/StarDocs/LedMod/LedModEffects/

In the future it should be possible to search on tags

**Comment by ewoudwijma** [comment]
Please close if confirmed
