### ISSUE TITLE
ArtNet and DDP broken

### ISSUE THREAD

**Issue by netmindz** [ewoudwijma/StarMod#40]
Both DDP and ArtNet have the following code

`        if (ddpInst >=0 && ddpInst < instances->instances.size()) {
`
This fails as the value being passed by the option value is the last octet of the IP, so the `.size()` check will fail if your IP ends with a value greater than the number of instances, e.g 3 instance but your ips are 101,102,103

**Comment by ewowi** [comment]
Fixed here, please check: https://github.com/MoonModules/StarLeds/commit/e504c9dde9cc696bf0c0799c08fc6419a80aaac7

**Comment by ewoudwijma** [comment]
Fix is still a bit clumsy as we only need to add the first 3 segments of the ip (the 4th is the value)

but ip dropdowns will be replaced by instance name (mac-address as key) only as we don’t want to identify instances by ip

**Comment by netmindz** [comment]
Closing as not part of base
