### ISSUE TITLE
241 Rings - projection from point

### ISSUE THREAD

**Issue by netmindz** [ewoudwijma/StarMod#41]
Projection from point defaults to the 0,0 point, if you try and move to be the center of the rings to be able to use the AudioRings effect as intended, then you only get a projection in the top right quadrant, not full circles from that point

**Comment by ewoudwijma** [comment]
True, but WIP 🙂

Going through the projection mappings is high prio for weeks, but for some reason always other things come first 🙂

**Comment by ewoudwijma** [comment]
Can you retry with latest build as lot have been changed lately

**Comment by netmindz** [comment]
Closing as not a part of the base
