### ISSUE TITLE
No mDNS/.local address

### ISSUE THREAD

**Issue by Flavourdynamics** [ewoudwijma/StarMod#47]
Problem:
Following the instructions to flash version 24040209 to ESP32-D0WDQ6 v4.4.6-dirty results in a generic hostname not accessible through mDNS/bonjour/.local address. 

Next Steps:
- Confirmation from other users would be helpful, as I have terrible network hardware.

**Comment by ewowi** [comment]
both WLED and StarMod devices show a generated mdns name. WLED can specify a name like is done in humancube.

so my proposal is that StarMod devices show the instance name as long as it is not StarMod (the default)
If instance name is StarMod , then it will show star-escapedmac.

okay to implement that ?

@netmindz , any thoughts ?

**Comment by netmindz** [comment]
Sounds like a good plan

**Comment by Flavourdynamics** [comment]
With @netmindz considerations:

If the DCPC and mDNS hostnames are derived from the user specified "Name" field, there should be a mechanism to prevent invalid characters from being included into the Name field, or they should be substituted. I'm not sure if this is already part of the implementation, so disregard if so.

**Comment by ewowi** [comment]
Wifi hostname has now invalidcharacter removal, 
Mdns has ‘escapedmac’ which is macaddress without semicolon

but I propose that the instancename entered will already be cleaned from invalid characters directly (as you said) and the cleaned version will be used  for ap name, hostname, mdns name etc (all the same)

**Comment by ewowi** [comment]
Implemented in latest StarMod (Core) commit: https://github.com/ewowi/StarMod/commit/4f12da235bcee958b74f6d932b20a5ffcf9c449c

Following the new split of StarMod (Core) and StarMod Leds: Also merged downstream to StarMod Leds

StarDocs: See https://ewowi.github.io/StarDocs/SysMod/SysModSystem/ 

Please test in latest StarMod Core or Leds

**Comment by ewowi** [comment]
Implemented and tested
